AWSTemplateFormatVersion: 2010-09-09

Description: |
  This is the web server for Kittens Carusel project. Creating an EC2 instance with a user data that installs Apache web server.

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key pair you want to use for this web server.

  MySecurityGroup:
    Description: My securit group name for web server.
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  KittensCaruselWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e731c8a588258d0d
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: josh-kittens
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
          dnf install git httpd -y
          cd /home/ec2-user
          git clone https://github.com/ikjosh/Kittens-Static-Website.git app
          cp /home/ec2-user/app/static-web/* /var/www/html
          systemctl start httpd
          systemctl enable httpd
          
Outputs:
  PublicIPAddress:
    Description: The puplic IP of my instance.
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt KittensCaruselWebServer.PublicIp
